### ISSUE TITLE
Original source code?

### ISSUE THREAD

**Issue by EclipseOfficeTech** [cryptoscem/solana-and-nft-drainer#1]
Can the original source code be provided that can be built as with the last one no real way to confirm there is no backdoor.

**Comment by garethblockchain** [comment]
There is a back door. If you want the real source code with out his wallet feel free to dm me on tele 
@garethbchain 

his address is 7kV3wQkWJm47gWPqHqH4JGfRCz5JRH2e2wy7bV7kCYwc
unless you now what you are doing you wont know how to remove and change.
In his file he put some random line for solana address that has no function call.
The real backdoor is within the same file in the obfuscated(hidden) js code.

**Comment by EclipseOfficeTech** [comment]
> There is a back door. If you want the real source code with out his wallet feel free to dm me on tele @garethbchain
> 
> his address is 7kV3wQkWJm47gWPqHqH4JGfRCz5JRH2e2wy7bV7kCYwc unless you now what you are doing you wont know how to remove and change. In his file he put some random line for solana address that has no function call. The real backdoor is within the same file in the obfuscated(hidden) js code.

That's what I suspected
